# Generated by Django 5.2.17 on 2026-09-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('typical_titles', models.JSONField(blank=True, default=list)),
                ('career_levels', models.JSONField(blank=True, default=list)),
                ('interview_topics', models.JSONField(blank=True, default=list)),
                ('project_types', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('average_experience_years_min', models.PositiveIntegerField(default=0)),
                ('average_experience_years_max', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['track__category__display_order', 'track__display_order', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('tool', 'Tool'), ('domain', 'Domain'), ('language', 'Language'), ('certification', 'Certification')], default='technical', max_length=30)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('phase_number', models.PositiveIntegerField(default=1)),
                ('estimated_weeks', models.PositiveIntegerField(default=2)),
                ('is_required', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_phases', to='career_taxonomy.role')),
            ],
            options={
                'ordering': ['phase_number'],
            },
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('required', 'Required'), ('important', 'Important'), ('optional', 'Optional')], default='important', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('minimum_level', models.PositiveIntegerField(default=1, help_text='Expected skill level from 1 to 5.')),
                ('evidence_types', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_skills', to='career_taxonomy.role')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_skills', to='career_taxonomy.skill')),
            ],
            options={
                'ordering': ['-weight', 'skill__name'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('estimated_hours', models.PositiveIntegerField(default=5)),
                ('completion_criteria', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='career_taxonomy.roadmapphase')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_steps', to='career_taxonomy.skill')),
            ],
            options={
                'ordering': ['phase__phase_number', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='career_taxonomy.category')),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='career_taxonomy.track'),
        ),
        migrations.AddConstraint(
            model_name='roadmapphase',
            constraint=models.UniqueConstraint(fields=('role', 'phase_number'), name='unique_roadmap_phase_per_role'),
        ),
        migrations.AddConstraint(
            model_name='roleskill',
            constraint=models.UniqueConstraint(fields=('role', 'skill'), name='unique_skill_per_role'),
        ),
        migrations.AddConstraint(
            model_name='roadmapstep',
            constraint=models.UniqueConstraint(fields=('phase', 'step_number'), name='unique_roadmap_step_per_phase'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_track_per_category'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('track', 'name'), name='unique_role_per_track'),
        ),
    ]
