# Generated by Django 5.2.17 on 2026-08-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
