# Generated by Django 5.2.17 on 2026-09-10 17:46

import cvs.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_cv_extracted_text_cv_parsed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(storage=cvs.storage.CVFileStorage(), upload_to='cvs/'),
        ),
    ]
