# Generated by Django 5.2.17 on 2026-08-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
